version: '3.3'

services:

  consumer_one:
    build: consumer_one
    volumes:
      - ./consumer_one:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  consumer_two:
    build: consumer_two
    volumes:
      - ./consumer_two:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - mongo
      - rabbitmq

  consumer_three:
    build: consumer_three
    volumes:
      - ./consumer_three:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - mongo
      - rabbitmq
      
  consumer_four:
    build: consumer_four
    volumes:
      - ./consumer_four:/app
    environment:
      - PYTHONUNBUFFERED=1
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    depends_on:
      - mongo
      - rabbitmq
  
  mongo:
    image: mongo
    expose:
      - 27017
    ports:
      - 27107:27017

  producer:
    build: producer
    volumes:
      - ./producer:/app
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "3300:5672"
      - "8080:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
